//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.5
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from C:/Dev/GitHub/Compiler/Grammar\LittleBigC.g4 by ANTLR 4.5

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591

using System;
using System.Text;
using System.Diagnostics;
using System.Collections.Generic;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.5")]
[System.CLSCompliant(false)]
public partial class LittleBigCParser : Parser {
	public const int
		T__0=1, Break=2, Case=3, Continue=4, Else=5, Float=6, Bool=7, String=8, 
		Hashtable=9, For=10, If=11, Int=12, Return=13, Void=14, While=15, New=16, 
		LeftParen=17, RightParen=18, LeftBracket=19, RightBracket=20, LeftBrace=21, 
		RightBrace=22, Less=23, LessEqual=24, Greater=25, GreaterEqual=26, Plus=27, 
		Minus=28, Star=29, Div=30, Mod=31, AndAnd=32, OrOr=33, Not=34, Semi=35, 
		Comma=36, Assign=37, Equal=38, NotEqual=39, Dot=40, Identifier=41, Constant=42, 
		IntegerConstant=43, BooleanConstant=44, Whitespace=45, Newline=46, BlockComment=47, 
		LineComment=48;
	public const int
		RULE_compilationUnit = 0, RULE_translationUnit = 1, RULE_externalDeclaration = 2, 
		RULE_variableType = 3, RULE_simpleVariableType = 4, RULE_variableDeclaration = 5, 
		RULE_initExpression = 6, RULE_arrayInitExpression = 7, RULE_functionDefinition = 8, 
		RULE_formalParameters = 9, RULE_formalParameter = 10, RULE_blockItemList = 11, 
		RULE_blockItem = 12, RULE_statement = 13, RULE_compoundStatement = 14, 
		RULE_expressionStatement = 15, RULE_selectionStatement = 16, RULE_iterationStatement = 17, 
		RULE_jumpStatement = 18, RULE_primaryExpression = 19, RULE_postfixExpression = 20, 
		RULE_argumentExpressionList = 21, RULE_multiplicativeExpression = 22, 
		RULE_additiveExpression = 23, RULE_relationalExpression = 24, RULE_equalityExpression = 25, 
		RULE_logicalAndExpression = 26, RULE_logicalOrExpression = 27, RULE_assignmentExpression = 28, 
		RULE_expression = 29;
	public static readonly string[] ruleNames = {
		"compilationUnit", "translationUnit", "externalDeclaration", "variableType", 
		"simpleVariableType", "variableDeclaration", "initExpression", "arrayInitExpression", 
		"functionDefinition", "formalParameters", "formalParameter", "blockItemList", 
		"blockItem", "statement", "compoundStatement", "expressionStatement", 
		"selectionStatement", "iterationStatement", "jumpStatement", "primaryExpression", 
		"postfixExpression", "argumentExpressionList", "multiplicativeExpression", 
		"additiveExpression", "relationalExpression", "equalityExpression", "logicalAndExpression", 
		"logicalOrExpression", "assignmentExpression", "expression"
	};

	private static readonly string[] _LiteralNames = {
		null, "'[]'", "'break'", "'case'", "'continue'", "'else'", "'float'", 
		"'bool'", "'string'", "'hashtable'", "'for'", "'if'", "'int'", "'return'", 
		"'void'", "'while'", "'new'", "'('", "')'", "'['", "']'", "'{'", "'}'", 
		"'<'", "'<='", "'>'", "'>='", "'+'", "'-'", "'*'", "'/'", "'%'", "'&&'", 
		"'||'", "'!'", "';'", "','", "'='", "'=='", "'!='", "'.'"
	};
	private static readonly string[] _SymbolicNames = {
		null, null, "Break", "Case", "Continue", "Else", "Float", "Bool", "String", 
		"Hashtable", "For", "If", "Int", "Return", "Void", "While", "New", "LeftParen", 
		"RightParen", "LeftBracket", "RightBracket", "LeftBrace", "RightBrace", 
		"Less", "LessEqual", "Greater", "GreaterEqual", "Plus", "Minus", "Star", 
		"Div", "Mod", "AndAnd", "OrOr", "Not", "Semi", "Comma", "Assign", "Equal", 
		"NotEqual", "Dot", "Identifier", "Constant", "IntegerConstant", "BooleanConstant", 
		"Whitespace", "Newline", "BlockComment", "LineComment"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "LittleBigC.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override string SerializedAtn { get { return _serializedATN; } }

	public LittleBigCParser(ITokenStream input)
		: base(input)
	{
		Interpreter = new ParserATNSimulator(this,_ATN);
	}
	public partial class CompilationUnitContext : ParserRuleContext {
		public ITerminalNode Eof() { return GetToken(LittleBigCParser.Eof, 0); }
		public TranslationUnitContext translationUnit() {
			return GetRuleContext<TranslationUnitContext>(0);
		}
		public CompilationUnitContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_compilationUnit; } }
		public override void EnterRule(IParseTreeListener listener) {
			ILittleBigCListener typedListener = listener as ILittleBigCListener;
			if (typedListener != null) typedListener.EnterCompilationUnit(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ILittleBigCListener typedListener = listener as ILittleBigCListener;
			if (typedListener != null) typedListener.ExitCompilationUnit(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ILittleBigCVisitor<TResult> typedVisitor = visitor as ILittleBigCVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitCompilationUnit(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public CompilationUnitContext compilationUnit() {
		CompilationUnitContext _localctx = new CompilationUnitContext(Context, State);
		EnterRule(_localctx, 0, RULE_compilationUnit);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 61;
			_la = TokenStream.La(1);
			if ((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << Float) | (1L << Bool) | (1L << String) | (1L << Hashtable) | (1L << Int) | (1L << Void) | (1L << Semi))) != 0)) {
				{
				State = 60; translationUnit(0);
				}
			}

			State = 63; Match(Eof);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class TranslationUnitContext : ParserRuleContext {
		public ExternalDeclarationContext externalDeclaration() {
			return GetRuleContext<ExternalDeclarationContext>(0);
		}
		public TranslationUnitContext translationUnit() {
			return GetRuleContext<TranslationUnitContext>(0);
		}
		public TranslationUnitContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_translationUnit; } }
		public override void EnterRule(IParseTreeListener listener) {
			ILittleBigCListener typedListener = listener as ILittleBigCListener;
			if (typedListener != null) typedListener.EnterTranslationUnit(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ILittleBigCListener typedListener = listener as ILittleBigCListener;
			if (typedListener != null) typedListener.ExitTranslationUnit(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ILittleBigCVisitor<TResult> typedVisitor = visitor as ILittleBigCVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitTranslationUnit(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public TranslationUnitContext translationUnit() {
		return translationUnit(0);
	}

	private TranslationUnitContext translationUnit(int _p) {
		ParserRuleContext _parentctx = Context;
		int _parentState = State;
		TranslationUnitContext _localctx = new TranslationUnitContext(Context, _parentState);
		TranslationUnitContext _prevctx = _localctx;
		int _startState = 2;
		EnterRecursionRule(_localctx, 2, RULE_translationUnit, _p);
		try {
			int _alt;
			EnterOuterAlt(_localctx, 1);
			{
			{
			State = 66; externalDeclaration();
			}
			Context.Stop = TokenStream.Lt(-1);
			State = 72;
			ErrorHandler.Sync(this);
			_alt = Interpreter.AdaptivePredict(TokenStream,1,Context);
			while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.InvalidAltNumber ) {
				if ( _alt==1 ) {
					if ( ParseListeners!=null ) 
						TriggerExitRuleEvent();
					_prevctx = _localctx;
					{
					{
					_localctx = new TranslationUnitContext(_parentctx, _parentState);
					PushNewRecursionContext(_localctx, _startState, RULE_translationUnit);
					State = 68;
					if (!(Precpred(Context, 1))) throw new FailedPredicateException(this, "Precpred(Context, 1)");
					State = 69; externalDeclaration();
					}
					} 
				}
				State = 74;
				ErrorHandler.Sync(this);
				_alt = Interpreter.AdaptivePredict(TokenStream,1,Context);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			UnrollRecursionContexts(_parentctx);
		}
		return _localctx;
	}

	public partial class ExternalDeclarationContext : ParserRuleContext {
		public FunctionDefinitionContext functionDefinition() {
			return GetRuleContext<FunctionDefinitionContext>(0);
		}
		public VariableDeclarationContext variableDeclaration() {
			return GetRuleContext<VariableDeclarationContext>(0);
		}
		public ExternalDeclarationContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_externalDeclaration; } }
		public override void EnterRule(IParseTreeListener listener) {
			ILittleBigCListener typedListener = listener as ILittleBigCListener;
			if (typedListener != null) typedListener.EnterExternalDeclaration(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ILittleBigCListener typedListener = listener as ILittleBigCListener;
			if (typedListener != null) typedListener.ExitExternalDeclaration(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ILittleBigCVisitor<TResult> typedVisitor = visitor as ILittleBigCVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitExternalDeclaration(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ExternalDeclarationContext externalDeclaration() {
		ExternalDeclarationContext _localctx = new ExternalDeclarationContext(Context, State);
		EnterRule(_localctx, 4, RULE_externalDeclaration);
		try {
			State = 78;
			switch ( Interpreter.AdaptivePredict(TokenStream,2,Context) ) {
			case 1:
				EnterOuterAlt(_localctx, 1);
				{
				State = 75; functionDefinition();
				}
				break;
			case 2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 76; variableDeclaration();
				}
				break;
			case 3:
				EnterOuterAlt(_localctx, 3);
				{
				State = 77; Match(Semi);
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class VariableTypeContext : ParserRuleContext {
		public SimpleVariableTypeContext simpleVariableType() {
			return GetRuleContext<SimpleVariableTypeContext>(0);
		}
		public VariableTypeContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_variableType; } }
		public override void EnterRule(IParseTreeListener listener) {
			ILittleBigCListener typedListener = listener as ILittleBigCListener;
			if (typedListener != null) typedListener.EnterVariableType(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ILittleBigCListener typedListener = listener as ILittleBigCListener;
			if (typedListener != null) typedListener.ExitVariableType(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ILittleBigCVisitor<TResult> typedVisitor = visitor as ILittleBigCVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitVariableType(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public VariableTypeContext variableType() {
		VariableTypeContext _localctx = new VariableTypeContext(Context, State);
		EnterRule(_localctx, 6, RULE_variableType);
		try {
			State = 85;
			switch ( Interpreter.AdaptivePredict(TokenStream,3,Context) ) {
			case 1:
				EnterOuterAlt(_localctx, 1);
				{
				State = 80; simpleVariableType();
				}
				break;
			case 2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 81; simpleVariableType();
				State = 82; Match(T__0);
				}
				break;
			case 3:
				EnterOuterAlt(_localctx, 3);
				{
				State = 84; Match(Void);
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class SimpleVariableTypeContext : ParserRuleContext {
		public SimpleVariableTypeContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_simpleVariableType; } }
		public override void EnterRule(IParseTreeListener listener) {
			ILittleBigCListener typedListener = listener as ILittleBigCListener;
			if (typedListener != null) typedListener.EnterSimpleVariableType(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ILittleBigCListener typedListener = listener as ILittleBigCListener;
			if (typedListener != null) typedListener.ExitSimpleVariableType(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ILittleBigCVisitor<TResult> typedVisitor = visitor as ILittleBigCVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitSimpleVariableType(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public SimpleVariableTypeContext simpleVariableType() {
		SimpleVariableTypeContext _localctx = new SimpleVariableTypeContext(Context, State);
		EnterRule(_localctx, 8, RULE_simpleVariableType);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 87;
			_la = TokenStream.La(1);
			if ( !((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << Float) | (1L << Bool) | (1L << String) | (1L << Hashtable) | (1L << Int))) != 0)) ) {
			ErrorHandler.RecoverInline(this);
			}
			Consume();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class VariableDeclarationContext : ParserRuleContext {
		public VariableTypeContext variableType() {
			return GetRuleContext<VariableTypeContext>(0);
		}
		public ITerminalNode Identifier() { return GetToken(LittleBigCParser.Identifier, 0); }
		public InitExpressionContext initExpression() {
			return GetRuleContext<InitExpressionContext>(0);
		}
		public VariableDeclarationContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_variableDeclaration; } }
		public override void EnterRule(IParseTreeListener listener) {
			ILittleBigCListener typedListener = listener as ILittleBigCListener;
			if (typedListener != null) typedListener.EnterVariableDeclaration(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ILittleBigCListener typedListener = listener as ILittleBigCListener;
			if (typedListener != null) typedListener.ExitVariableDeclaration(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ILittleBigCVisitor<TResult> typedVisitor = visitor as ILittleBigCVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitVariableDeclaration(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public VariableDeclarationContext variableDeclaration() {
		VariableDeclarationContext _localctx = new VariableDeclarationContext(Context, State);
		EnterRule(_localctx, 10, RULE_variableDeclaration);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 89; variableType();
			State = 90; Match(Identifier);
			State = 93;
			_la = TokenStream.La(1);
			if (_la==Assign) {
				{
				State = 91; Match(Assign);
				State = 92; initExpression();
				}
			}

			State = 95; Match(Semi);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class InitExpressionContext : ParserRuleContext {
		public ExpressionContext expression() {
			return GetRuleContext<ExpressionContext>(0);
		}
		public ITerminalNode Constant() { return GetToken(LittleBigCParser.Constant, 0); }
		public ArrayInitExpressionContext arrayInitExpression() {
			return GetRuleContext<ArrayInitExpressionContext>(0);
		}
		public InitExpressionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_initExpression; } }
		public override void EnterRule(IParseTreeListener listener) {
			ILittleBigCListener typedListener = listener as ILittleBigCListener;
			if (typedListener != null) typedListener.EnterInitExpression(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ILittleBigCListener typedListener = listener as ILittleBigCListener;
			if (typedListener != null) typedListener.ExitInitExpression(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ILittleBigCVisitor<TResult> typedVisitor = visitor as ILittleBigCVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitInitExpression(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public InitExpressionContext initExpression() {
		InitExpressionContext _localctx = new InitExpressionContext(Context, State);
		EnterRule(_localctx, 12, RULE_initExpression);
		try {
			State = 100;
			switch ( Interpreter.AdaptivePredict(TokenStream,5,Context) ) {
			case 1:
				EnterOuterAlt(_localctx, 1);
				{
				State = 97; expression();
				}
				break;
			case 2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 98; Match(Constant);
				}
				break;
			case 3:
				EnterOuterAlt(_localctx, 3);
				{
				State = 99; arrayInitExpression();
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ArrayInitExpressionContext : ParserRuleContext {
		public SimpleVariableTypeContext simpleVariableType() {
			return GetRuleContext<SimpleVariableTypeContext>(0);
		}
		public ExpressionContext expression() {
			return GetRuleContext<ExpressionContext>(0);
		}
		public ArrayInitExpressionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_arrayInitExpression; } }
		public override void EnterRule(IParseTreeListener listener) {
			ILittleBigCListener typedListener = listener as ILittleBigCListener;
			if (typedListener != null) typedListener.EnterArrayInitExpression(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ILittleBigCListener typedListener = listener as ILittleBigCListener;
			if (typedListener != null) typedListener.ExitArrayInitExpression(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ILittleBigCVisitor<TResult> typedVisitor = visitor as ILittleBigCVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitArrayInitExpression(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ArrayInitExpressionContext arrayInitExpression() {
		ArrayInitExpressionContext _localctx = new ArrayInitExpressionContext(Context, State);
		EnterRule(_localctx, 14, RULE_arrayInitExpression);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 102; Match(New);
			State = 103; simpleVariableType();
			State = 104; Match(LeftBracket);
			State = 105; expression();
			State = 106; Match(RightBracket);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class FunctionDefinitionContext : ParserRuleContext {
		public VariableTypeContext variableType() {
			return GetRuleContext<VariableTypeContext>(0);
		}
		public ITerminalNode Identifier() { return GetToken(LittleBigCParser.Identifier, 0); }
		public CompoundStatementContext compoundStatement() {
			return GetRuleContext<CompoundStatementContext>(0);
		}
		public FormalParametersContext formalParameters() {
			return GetRuleContext<FormalParametersContext>(0);
		}
		public FunctionDefinitionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_functionDefinition; } }
		public override void EnterRule(IParseTreeListener listener) {
			ILittleBigCListener typedListener = listener as ILittleBigCListener;
			if (typedListener != null) typedListener.EnterFunctionDefinition(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ILittleBigCListener typedListener = listener as ILittleBigCListener;
			if (typedListener != null) typedListener.ExitFunctionDefinition(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ILittleBigCVisitor<TResult> typedVisitor = visitor as ILittleBigCVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitFunctionDefinition(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public FunctionDefinitionContext functionDefinition() {
		FunctionDefinitionContext _localctx = new FunctionDefinitionContext(Context, State);
		EnterRule(_localctx, 16, RULE_functionDefinition);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 108; variableType();
			State = 109; Match(Identifier);
			State = 110; Match(LeftParen);
			State = 112;
			_la = TokenStream.La(1);
			if ((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << Float) | (1L << Bool) | (1L << String) | (1L << Hashtable) | (1L << Int) | (1L << Void))) != 0)) {
				{
				State = 111; formalParameters(0);
				}
			}

			State = 114; Match(RightParen);
			State = 115; compoundStatement();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class FormalParametersContext : ParserRuleContext {
		public FormalParameterContext formalParameter() {
			return GetRuleContext<FormalParameterContext>(0);
		}
		public FormalParametersContext formalParameters() {
			return GetRuleContext<FormalParametersContext>(0);
		}
		public FormalParametersContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_formalParameters; } }
		public override void EnterRule(IParseTreeListener listener) {
			ILittleBigCListener typedListener = listener as ILittleBigCListener;
			if (typedListener != null) typedListener.EnterFormalParameters(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ILittleBigCListener typedListener = listener as ILittleBigCListener;
			if (typedListener != null) typedListener.ExitFormalParameters(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ILittleBigCVisitor<TResult> typedVisitor = visitor as ILittleBigCVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitFormalParameters(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public FormalParametersContext formalParameters() {
		return formalParameters(0);
	}

	private FormalParametersContext formalParameters(int _p) {
		ParserRuleContext _parentctx = Context;
		int _parentState = State;
		FormalParametersContext _localctx = new FormalParametersContext(Context, _parentState);
		FormalParametersContext _prevctx = _localctx;
		int _startState = 18;
		EnterRecursionRule(_localctx, 18, RULE_formalParameters, _p);
		try {
			int _alt;
			EnterOuterAlt(_localctx, 1);
			{
			{
			State = 118; formalParameter();
			}
			Context.Stop = TokenStream.Lt(-1);
			State = 125;
			ErrorHandler.Sync(this);
			_alt = Interpreter.AdaptivePredict(TokenStream,7,Context);
			while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.InvalidAltNumber ) {
				if ( _alt==1 ) {
					if ( ParseListeners!=null ) 
						TriggerExitRuleEvent();
					_prevctx = _localctx;
					{
					{
					_localctx = new FormalParametersContext(_parentctx, _parentState);
					PushNewRecursionContext(_localctx, _startState, RULE_formalParameters);
					State = 120;
					if (!(Precpred(Context, 1))) throw new FailedPredicateException(this, "Precpred(Context, 1)");
					State = 121; Match(Comma);
					State = 122; formalParameter();
					}
					} 
				}
				State = 127;
				ErrorHandler.Sync(this);
				_alt = Interpreter.AdaptivePredict(TokenStream,7,Context);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			UnrollRecursionContexts(_parentctx);
		}
		return _localctx;
	}

	public partial class FormalParameterContext : ParserRuleContext {
		public VariableTypeContext variableType() {
			return GetRuleContext<VariableTypeContext>(0);
		}
		public ITerminalNode Identifier() { return GetToken(LittleBigCParser.Identifier, 0); }
		public FormalParameterContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_formalParameter; } }
		public override void EnterRule(IParseTreeListener listener) {
			ILittleBigCListener typedListener = listener as ILittleBigCListener;
			if (typedListener != null) typedListener.EnterFormalParameter(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ILittleBigCListener typedListener = listener as ILittleBigCListener;
			if (typedListener != null) typedListener.ExitFormalParameter(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ILittleBigCVisitor<TResult> typedVisitor = visitor as ILittleBigCVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitFormalParameter(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public FormalParameterContext formalParameter() {
		FormalParameterContext _localctx = new FormalParameterContext(Context, State);
		EnterRule(_localctx, 20, RULE_formalParameter);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 128; variableType();
			State = 129; Match(Identifier);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class BlockItemListContext : ParserRuleContext {
		public BlockItemContext blockItem() {
			return GetRuleContext<BlockItemContext>(0);
		}
		public BlockItemListContext blockItemList() {
			return GetRuleContext<BlockItemListContext>(0);
		}
		public BlockItemListContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_blockItemList; } }
		public override void EnterRule(IParseTreeListener listener) {
			ILittleBigCListener typedListener = listener as ILittleBigCListener;
			if (typedListener != null) typedListener.EnterBlockItemList(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ILittleBigCListener typedListener = listener as ILittleBigCListener;
			if (typedListener != null) typedListener.ExitBlockItemList(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ILittleBigCVisitor<TResult> typedVisitor = visitor as ILittleBigCVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitBlockItemList(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public BlockItemListContext blockItemList() {
		return blockItemList(0);
	}

	private BlockItemListContext blockItemList(int _p) {
		ParserRuleContext _parentctx = Context;
		int _parentState = State;
		BlockItemListContext _localctx = new BlockItemListContext(Context, _parentState);
		BlockItemListContext _prevctx = _localctx;
		int _startState = 22;
		EnterRecursionRule(_localctx, 22, RULE_blockItemList, _p);
		try {
			int _alt;
			EnterOuterAlt(_localctx, 1);
			{
			{
			State = 132; blockItem();
			}
			Context.Stop = TokenStream.Lt(-1);
			State = 138;
			ErrorHandler.Sync(this);
			_alt = Interpreter.AdaptivePredict(TokenStream,8,Context);
			while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.InvalidAltNumber ) {
				if ( _alt==1 ) {
					if ( ParseListeners!=null ) 
						TriggerExitRuleEvent();
					_prevctx = _localctx;
					{
					{
					_localctx = new BlockItemListContext(_parentctx, _parentState);
					PushNewRecursionContext(_localctx, _startState, RULE_blockItemList);
					State = 134;
					if (!(Precpred(Context, 1))) throw new FailedPredicateException(this, "Precpred(Context, 1)");
					State = 135; blockItem();
					}
					} 
				}
				State = 140;
				ErrorHandler.Sync(this);
				_alt = Interpreter.AdaptivePredict(TokenStream,8,Context);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			UnrollRecursionContexts(_parentctx);
		}
		return _localctx;
	}

	public partial class BlockItemContext : ParserRuleContext {
		public VariableDeclarationContext variableDeclaration() {
			return GetRuleContext<VariableDeclarationContext>(0);
		}
		public StatementContext statement() {
			return GetRuleContext<StatementContext>(0);
		}
		public BlockItemContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_blockItem; } }
		public override void EnterRule(IParseTreeListener listener) {
			ILittleBigCListener typedListener = listener as ILittleBigCListener;
			if (typedListener != null) typedListener.EnterBlockItem(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ILittleBigCListener typedListener = listener as ILittleBigCListener;
			if (typedListener != null) typedListener.ExitBlockItem(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ILittleBigCVisitor<TResult> typedVisitor = visitor as ILittleBigCVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitBlockItem(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public BlockItemContext blockItem() {
		BlockItemContext _localctx = new BlockItemContext(Context, State);
		EnterRule(_localctx, 24, RULE_blockItem);
		try {
			State = 143;
			switch (TokenStream.La(1)) {
			case Float:
			case Bool:
			case String:
			case Hashtable:
			case Int:
			case Void:
				EnterOuterAlt(_localctx, 1);
				{
				State = 141; variableDeclaration();
				}
				break;
			case Break:
			case Continue:
			case For:
			case If:
			case Return:
			case While:
			case LeftParen:
			case LeftBrace:
			case Semi:
			case Identifier:
			case Constant:
				EnterOuterAlt(_localctx, 2);
				{
				State = 142; statement();
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class StatementContext : ParserRuleContext {
		public CompoundStatementContext compoundStatement() {
			return GetRuleContext<CompoundStatementContext>(0);
		}
		public ExpressionStatementContext expressionStatement() {
			return GetRuleContext<ExpressionStatementContext>(0);
		}
		public SelectionStatementContext selectionStatement() {
			return GetRuleContext<SelectionStatementContext>(0);
		}
		public IterationStatementContext iterationStatement() {
			return GetRuleContext<IterationStatementContext>(0);
		}
		public JumpStatementContext jumpStatement() {
			return GetRuleContext<JumpStatementContext>(0);
		}
		public StatementContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_statement; } }
		public override void EnterRule(IParseTreeListener listener) {
			ILittleBigCListener typedListener = listener as ILittleBigCListener;
			if (typedListener != null) typedListener.EnterStatement(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ILittleBigCListener typedListener = listener as ILittleBigCListener;
			if (typedListener != null) typedListener.ExitStatement(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ILittleBigCVisitor<TResult> typedVisitor = visitor as ILittleBigCVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitStatement(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public StatementContext statement() {
		StatementContext _localctx = new StatementContext(Context, State);
		EnterRule(_localctx, 26, RULE_statement);
		try {
			State = 150;
			switch (TokenStream.La(1)) {
			case LeftBrace:
				EnterOuterAlt(_localctx, 1);
				{
				State = 145; compoundStatement();
				}
				break;
			case LeftParen:
			case Semi:
			case Identifier:
			case Constant:
				EnterOuterAlt(_localctx, 2);
				{
				State = 146; expressionStatement();
				}
				break;
			case If:
				EnterOuterAlt(_localctx, 3);
				{
				State = 147; selectionStatement();
				}
				break;
			case For:
			case While:
				EnterOuterAlt(_localctx, 4);
				{
				State = 148; iterationStatement();
				}
				break;
			case Break:
			case Continue:
			case Return:
				EnterOuterAlt(_localctx, 5);
				{
				State = 149; jumpStatement();
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class CompoundStatementContext : ParserRuleContext {
		public BlockItemListContext blockItemList() {
			return GetRuleContext<BlockItemListContext>(0);
		}
		public CompoundStatementContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_compoundStatement; } }
		public override void EnterRule(IParseTreeListener listener) {
			ILittleBigCListener typedListener = listener as ILittleBigCListener;
			if (typedListener != null) typedListener.EnterCompoundStatement(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ILittleBigCListener typedListener = listener as ILittleBigCListener;
			if (typedListener != null) typedListener.ExitCompoundStatement(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ILittleBigCVisitor<TResult> typedVisitor = visitor as ILittleBigCVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitCompoundStatement(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public CompoundStatementContext compoundStatement() {
		CompoundStatementContext _localctx = new CompoundStatementContext(Context, State);
		EnterRule(_localctx, 28, RULE_compoundStatement);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 152; Match(LeftBrace);
			State = 154;
			_la = TokenStream.La(1);
			if ((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << Break) | (1L << Continue) | (1L << Float) | (1L << Bool) | (1L << String) | (1L << Hashtable) | (1L << For) | (1L << If) | (1L << Int) | (1L << Return) | (1L << Void) | (1L << While) | (1L << LeftParen) | (1L << LeftBrace) | (1L << Semi) | (1L << Identifier) | (1L << Constant))) != 0)) {
				{
				State = 153; blockItemList(0);
				}
			}

			State = 156; Match(RightBrace);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ExpressionStatementContext : ParserRuleContext {
		public ExpressionContext expression() {
			return GetRuleContext<ExpressionContext>(0);
		}
		public ExpressionStatementContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_expressionStatement; } }
		public override void EnterRule(IParseTreeListener listener) {
			ILittleBigCListener typedListener = listener as ILittleBigCListener;
			if (typedListener != null) typedListener.EnterExpressionStatement(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ILittleBigCListener typedListener = listener as ILittleBigCListener;
			if (typedListener != null) typedListener.ExitExpressionStatement(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ILittleBigCVisitor<TResult> typedVisitor = visitor as ILittleBigCVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitExpressionStatement(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ExpressionStatementContext expressionStatement() {
		ExpressionStatementContext _localctx = new ExpressionStatementContext(Context, State);
		EnterRule(_localctx, 30, RULE_expressionStatement);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 159;
			_la = TokenStream.La(1);
			if ((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << LeftParen) | (1L << Identifier) | (1L << Constant))) != 0)) {
				{
				State = 158; expression();
				}
			}

			State = 161; Match(Semi);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class SelectionStatementContext : ParserRuleContext {
		public ExpressionContext expression() {
			return GetRuleContext<ExpressionContext>(0);
		}
		public StatementContext[] statement() {
			return GetRuleContexts<StatementContext>();
		}
		public StatementContext statement(int i) {
			return GetRuleContext<StatementContext>(i);
		}
		public SelectionStatementContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_selectionStatement; } }
		public override void EnterRule(IParseTreeListener listener) {
			ILittleBigCListener typedListener = listener as ILittleBigCListener;
			if (typedListener != null) typedListener.EnterSelectionStatement(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ILittleBigCListener typedListener = listener as ILittleBigCListener;
			if (typedListener != null) typedListener.ExitSelectionStatement(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ILittleBigCVisitor<TResult> typedVisitor = visitor as ILittleBigCVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitSelectionStatement(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public SelectionStatementContext selectionStatement() {
		SelectionStatementContext _localctx = new SelectionStatementContext(Context, State);
		EnterRule(_localctx, 32, RULE_selectionStatement);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 163; Match(If);
			State = 164; Match(LeftParen);
			State = 165; expression();
			State = 166; Match(RightParen);
			State = 167; statement();
			State = 170;
			switch ( Interpreter.AdaptivePredict(TokenStream,13,Context) ) {
			case 1:
				{
				State = 168; Match(Else);
				State = 169; statement();
				}
				break;
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class IterationStatementContext : ParserRuleContext {
		public ExpressionContext[] expression() {
			return GetRuleContexts<ExpressionContext>();
		}
		public ExpressionContext expression(int i) {
			return GetRuleContext<ExpressionContext>(i);
		}
		public StatementContext statement() {
			return GetRuleContext<StatementContext>(0);
		}
		public IterationStatementContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_iterationStatement; } }
		public override void EnterRule(IParseTreeListener listener) {
			ILittleBigCListener typedListener = listener as ILittleBigCListener;
			if (typedListener != null) typedListener.EnterIterationStatement(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ILittleBigCListener typedListener = listener as ILittleBigCListener;
			if (typedListener != null) typedListener.ExitIterationStatement(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ILittleBigCVisitor<TResult> typedVisitor = visitor as ILittleBigCVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitIterationStatement(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public IterationStatementContext iterationStatement() {
		IterationStatementContext _localctx = new IterationStatementContext(Context, State);
		EnterRule(_localctx, 34, RULE_iterationStatement);
		int _la;
		try {
			State = 193;
			switch (TokenStream.La(1)) {
			case While:
				EnterOuterAlt(_localctx, 1);
				{
				State = 172; Match(While);
				State = 173; Match(LeftParen);
				State = 174; expression();
				State = 175; Match(RightParen);
				State = 176; statement();
				}
				break;
			case For:
				EnterOuterAlt(_localctx, 2);
				{
				State = 178; Match(For);
				State = 179; Match(LeftParen);
				State = 181;
				_la = TokenStream.La(1);
				if ((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << LeftParen) | (1L << Identifier) | (1L << Constant))) != 0)) {
					{
					State = 180; expression();
					}
				}

				State = 183; Match(Semi);
				State = 185;
				_la = TokenStream.La(1);
				if ((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << LeftParen) | (1L << Identifier) | (1L << Constant))) != 0)) {
					{
					State = 184; expression();
					}
				}

				State = 187; Match(Semi);
				State = 189;
				_la = TokenStream.La(1);
				if ((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << LeftParen) | (1L << Identifier) | (1L << Constant))) != 0)) {
					{
					State = 188; expression();
					}
				}

				State = 191; Match(RightParen);
				State = 192; statement();
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class JumpStatementContext : ParserRuleContext {
		public ExpressionContext expression() {
			return GetRuleContext<ExpressionContext>(0);
		}
		public JumpStatementContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_jumpStatement; } }
		public override void EnterRule(IParseTreeListener listener) {
			ILittleBigCListener typedListener = listener as ILittleBigCListener;
			if (typedListener != null) typedListener.EnterJumpStatement(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ILittleBigCListener typedListener = listener as ILittleBigCListener;
			if (typedListener != null) typedListener.ExitJumpStatement(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ILittleBigCVisitor<TResult> typedVisitor = visitor as ILittleBigCVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitJumpStatement(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public JumpStatementContext jumpStatement() {
		JumpStatementContext _localctx = new JumpStatementContext(Context, State);
		EnterRule(_localctx, 36, RULE_jumpStatement);
		int _la;
		try {
			State = 204;
			switch (TokenStream.La(1)) {
			case Continue:
				EnterOuterAlt(_localctx, 1);
				{
				State = 195; Match(Continue);
				State = 196; Match(Semi);
				}
				break;
			case Break:
				EnterOuterAlt(_localctx, 2);
				{
				State = 197; Match(Break);
				State = 198; Match(Semi);
				}
				break;
			case Return:
				EnterOuterAlt(_localctx, 3);
				{
				State = 199; Match(Return);
				State = 201;
				_la = TokenStream.La(1);
				if ((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << LeftParen) | (1L << Identifier) | (1L << Constant))) != 0)) {
					{
					State = 200; expression();
					}
				}

				State = 203; Match(Semi);
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class PrimaryExpressionContext : ParserRuleContext {
		public ITerminalNode Identifier() { return GetToken(LittleBigCParser.Identifier, 0); }
		public ITerminalNode Constant() { return GetToken(LittleBigCParser.Constant, 0); }
		public ExpressionContext expression() {
			return GetRuleContext<ExpressionContext>(0);
		}
		public PrimaryExpressionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_primaryExpression; } }
		public override void EnterRule(IParseTreeListener listener) {
			ILittleBigCListener typedListener = listener as ILittleBigCListener;
			if (typedListener != null) typedListener.EnterPrimaryExpression(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ILittleBigCListener typedListener = listener as ILittleBigCListener;
			if (typedListener != null) typedListener.ExitPrimaryExpression(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ILittleBigCVisitor<TResult> typedVisitor = visitor as ILittleBigCVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitPrimaryExpression(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public PrimaryExpressionContext primaryExpression() {
		PrimaryExpressionContext _localctx = new PrimaryExpressionContext(Context, State);
		EnterRule(_localctx, 38, RULE_primaryExpression);
		try {
			State = 212;
			switch (TokenStream.La(1)) {
			case Identifier:
				EnterOuterAlt(_localctx, 1);
				{
				State = 206; Match(Identifier);
				}
				break;
			case Constant:
				EnterOuterAlt(_localctx, 2);
				{
				State = 207; Match(Constant);
				}
				break;
			case LeftParen:
				EnterOuterAlt(_localctx, 3);
				{
				State = 208; Match(LeftParen);
				State = 209; expression();
				State = 210; Match(RightParen);
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class PostfixExpressionContext : ParserRuleContext {
		public PrimaryExpressionContext primaryExpression() {
			return GetRuleContext<PrimaryExpressionContext>(0);
		}
		public PostfixExpressionContext postfixExpression() {
			return GetRuleContext<PostfixExpressionContext>(0);
		}
		public ExpressionContext expression() {
			return GetRuleContext<ExpressionContext>(0);
		}
		public ArgumentExpressionListContext argumentExpressionList() {
			return GetRuleContext<ArgumentExpressionListContext>(0);
		}
		public PostfixExpressionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_postfixExpression; } }
		public override void EnterRule(IParseTreeListener listener) {
			ILittleBigCListener typedListener = listener as ILittleBigCListener;
			if (typedListener != null) typedListener.EnterPostfixExpression(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ILittleBigCListener typedListener = listener as ILittleBigCListener;
			if (typedListener != null) typedListener.ExitPostfixExpression(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ILittleBigCVisitor<TResult> typedVisitor = visitor as ILittleBigCVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitPostfixExpression(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public PostfixExpressionContext postfixExpression() {
		return postfixExpression(0);
	}

	private PostfixExpressionContext postfixExpression(int _p) {
		ParserRuleContext _parentctx = Context;
		int _parentState = State;
		PostfixExpressionContext _localctx = new PostfixExpressionContext(Context, _parentState);
		PostfixExpressionContext _prevctx = _localctx;
		int _startState = 40;
		EnterRecursionRule(_localctx, 40, RULE_postfixExpression, _p);
		int _la;
		try {
			int _alt;
			EnterOuterAlt(_localctx, 1);
			{
			{
			State = 215; primaryExpression();
			}
			Context.Stop = TokenStream.Lt(-1);
			State = 230;
			ErrorHandler.Sync(this);
			_alt = Interpreter.AdaptivePredict(TokenStream,23,Context);
			while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.InvalidAltNumber ) {
				if ( _alt==1 ) {
					if ( ParseListeners!=null ) 
						TriggerExitRuleEvent();
					_prevctx = _localctx;
					{
					State = 228;
					switch ( Interpreter.AdaptivePredict(TokenStream,22,Context) ) {
					case 1:
						{
						_localctx = new PostfixExpressionContext(_parentctx, _parentState);
						PushNewRecursionContext(_localctx, _startState, RULE_postfixExpression);
						State = 217;
						if (!(Precpred(Context, 2))) throw new FailedPredicateException(this, "Precpred(Context, 2)");
						State = 218; Match(LeftBracket);
						State = 219; expression();
						State = 220; Match(RightBracket);
						}
						break;
					case 2:
						{
						_localctx = new PostfixExpressionContext(_parentctx, _parentState);
						PushNewRecursionContext(_localctx, _startState, RULE_postfixExpression);
						State = 222;
						if (!(Precpred(Context, 1))) throw new FailedPredicateException(this, "Precpred(Context, 1)");
						State = 223; Match(LeftParen);
						State = 225;
						_la = TokenStream.La(1);
						if ((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << LeftParen) | (1L << Identifier) | (1L << Constant))) != 0)) {
							{
							State = 224; argumentExpressionList(0);
							}
						}

						State = 227; Match(RightParen);
						}
						break;
					}
					} 
				}
				State = 232;
				ErrorHandler.Sync(this);
				_alt = Interpreter.AdaptivePredict(TokenStream,23,Context);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			UnrollRecursionContexts(_parentctx);
		}
		return _localctx;
	}

	public partial class ArgumentExpressionListContext : ParserRuleContext {
		public AssignmentExpressionContext assignmentExpression() {
			return GetRuleContext<AssignmentExpressionContext>(0);
		}
		public ArgumentExpressionListContext argumentExpressionList() {
			return GetRuleContext<ArgumentExpressionListContext>(0);
		}
		public ArgumentExpressionListContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_argumentExpressionList; } }
		public override void EnterRule(IParseTreeListener listener) {
			ILittleBigCListener typedListener = listener as ILittleBigCListener;
			if (typedListener != null) typedListener.EnterArgumentExpressionList(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ILittleBigCListener typedListener = listener as ILittleBigCListener;
			if (typedListener != null) typedListener.ExitArgumentExpressionList(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ILittleBigCVisitor<TResult> typedVisitor = visitor as ILittleBigCVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitArgumentExpressionList(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ArgumentExpressionListContext argumentExpressionList() {
		return argumentExpressionList(0);
	}

	private ArgumentExpressionListContext argumentExpressionList(int _p) {
		ParserRuleContext _parentctx = Context;
		int _parentState = State;
		ArgumentExpressionListContext _localctx = new ArgumentExpressionListContext(Context, _parentState);
		ArgumentExpressionListContext _prevctx = _localctx;
		int _startState = 42;
		EnterRecursionRule(_localctx, 42, RULE_argumentExpressionList, _p);
		try {
			int _alt;
			EnterOuterAlt(_localctx, 1);
			{
			{
			State = 234; assignmentExpression();
			}
			Context.Stop = TokenStream.Lt(-1);
			State = 241;
			ErrorHandler.Sync(this);
			_alt = Interpreter.AdaptivePredict(TokenStream,24,Context);
			while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.InvalidAltNumber ) {
				if ( _alt==1 ) {
					if ( ParseListeners!=null ) 
						TriggerExitRuleEvent();
					_prevctx = _localctx;
					{
					{
					_localctx = new ArgumentExpressionListContext(_parentctx, _parentState);
					PushNewRecursionContext(_localctx, _startState, RULE_argumentExpressionList);
					State = 236;
					if (!(Precpred(Context, 1))) throw new FailedPredicateException(this, "Precpred(Context, 1)");
					State = 237; Match(Comma);
					State = 238; assignmentExpression();
					}
					} 
				}
				State = 243;
				ErrorHandler.Sync(this);
				_alt = Interpreter.AdaptivePredict(TokenStream,24,Context);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			UnrollRecursionContexts(_parentctx);
		}
		return _localctx;
	}

	public partial class MultiplicativeExpressionContext : ParserRuleContext {
		public PostfixExpressionContext postfixExpression() {
			return GetRuleContext<PostfixExpressionContext>(0);
		}
		public MultiplicativeExpressionContext multiplicativeExpression() {
			return GetRuleContext<MultiplicativeExpressionContext>(0);
		}
		public MultiplicativeExpressionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_multiplicativeExpression; } }
		public override void EnterRule(IParseTreeListener listener) {
			ILittleBigCListener typedListener = listener as ILittleBigCListener;
			if (typedListener != null) typedListener.EnterMultiplicativeExpression(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ILittleBigCListener typedListener = listener as ILittleBigCListener;
			if (typedListener != null) typedListener.ExitMultiplicativeExpression(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ILittleBigCVisitor<TResult> typedVisitor = visitor as ILittleBigCVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitMultiplicativeExpression(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public MultiplicativeExpressionContext multiplicativeExpression() {
		return multiplicativeExpression(0);
	}

	private MultiplicativeExpressionContext multiplicativeExpression(int _p) {
		ParserRuleContext _parentctx = Context;
		int _parentState = State;
		MultiplicativeExpressionContext _localctx = new MultiplicativeExpressionContext(Context, _parentState);
		MultiplicativeExpressionContext _prevctx = _localctx;
		int _startState = 44;
		EnterRecursionRule(_localctx, 44, RULE_multiplicativeExpression, _p);
		try {
			int _alt;
			EnterOuterAlt(_localctx, 1);
			{
			{
			State = 245; postfixExpression(0);
			}
			Context.Stop = TokenStream.Lt(-1);
			State = 258;
			ErrorHandler.Sync(this);
			_alt = Interpreter.AdaptivePredict(TokenStream,26,Context);
			while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.InvalidAltNumber ) {
				if ( _alt==1 ) {
					if ( ParseListeners!=null ) 
						TriggerExitRuleEvent();
					_prevctx = _localctx;
					{
					State = 256;
					switch ( Interpreter.AdaptivePredict(TokenStream,25,Context) ) {
					case 1:
						{
						_localctx = new MultiplicativeExpressionContext(_parentctx, _parentState);
						PushNewRecursionContext(_localctx, _startState, RULE_multiplicativeExpression);
						State = 247;
						if (!(Precpred(Context, 3))) throw new FailedPredicateException(this, "Precpred(Context, 3)");
						State = 248; Match(Star);
						State = 249; postfixExpression(0);
						}
						break;
					case 2:
						{
						_localctx = new MultiplicativeExpressionContext(_parentctx, _parentState);
						PushNewRecursionContext(_localctx, _startState, RULE_multiplicativeExpression);
						State = 250;
						if (!(Precpred(Context, 2))) throw new FailedPredicateException(this, "Precpred(Context, 2)");
						State = 251; Match(Div);
						State = 252; postfixExpression(0);
						}
						break;
					case 3:
						{
						_localctx = new MultiplicativeExpressionContext(_parentctx, _parentState);
						PushNewRecursionContext(_localctx, _startState, RULE_multiplicativeExpression);
						State = 253;
						if (!(Precpred(Context, 1))) throw new FailedPredicateException(this, "Precpred(Context, 1)");
						State = 254; Match(Mod);
						State = 255; postfixExpression(0);
						}
						break;
					}
					} 
				}
				State = 260;
				ErrorHandler.Sync(this);
				_alt = Interpreter.AdaptivePredict(TokenStream,26,Context);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			UnrollRecursionContexts(_parentctx);
		}
		return _localctx;
	}

	public partial class AdditiveExpressionContext : ParserRuleContext {
		public MultiplicativeExpressionContext multiplicativeExpression() {
			return GetRuleContext<MultiplicativeExpressionContext>(0);
		}
		public AdditiveExpressionContext additiveExpression() {
			return GetRuleContext<AdditiveExpressionContext>(0);
		}
		public AdditiveExpressionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_additiveExpression; } }
		public override void EnterRule(IParseTreeListener listener) {
			ILittleBigCListener typedListener = listener as ILittleBigCListener;
			if (typedListener != null) typedListener.EnterAdditiveExpression(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ILittleBigCListener typedListener = listener as ILittleBigCListener;
			if (typedListener != null) typedListener.ExitAdditiveExpression(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ILittleBigCVisitor<TResult> typedVisitor = visitor as ILittleBigCVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitAdditiveExpression(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public AdditiveExpressionContext additiveExpression() {
		return additiveExpression(0);
	}

	private AdditiveExpressionContext additiveExpression(int _p) {
		ParserRuleContext _parentctx = Context;
		int _parentState = State;
		AdditiveExpressionContext _localctx = new AdditiveExpressionContext(Context, _parentState);
		AdditiveExpressionContext _prevctx = _localctx;
		int _startState = 46;
		EnterRecursionRule(_localctx, 46, RULE_additiveExpression, _p);
		try {
			int _alt;
			EnterOuterAlt(_localctx, 1);
			{
			{
			State = 262; multiplicativeExpression(0);
			}
			Context.Stop = TokenStream.Lt(-1);
			State = 272;
			ErrorHandler.Sync(this);
			_alt = Interpreter.AdaptivePredict(TokenStream,28,Context);
			while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.InvalidAltNumber ) {
				if ( _alt==1 ) {
					if ( ParseListeners!=null ) 
						TriggerExitRuleEvent();
					_prevctx = _localctx;
					{
					State = 270;
					switch ( Interpreter.AdaptivePredict(TokenStream,27,Context) ) {
					case 1:
						{
						_localctx = new AdditiveExpressionContext(_parentctx, _parentState);
						PushNewRecursionContext(_localctx, _startState, RULE_additiveExpression);
						State = 264;
						if (!(Precpred(Context, 2))) throw new FailedPredicateException(this, "Precpred(Context, 2)");
						State = 265; Match(Plus);
						State = 266; multiplicativeExpression(0);
						}
						break;
					case 2:
						{
						_localctx = new AdditiveExpressionContext(_parentctx, _parentState);
						PushNewRecursionContext(_localctx, _startState, RULE_additiveExpression);
						State = 267;
						if (!(Precpred(Context, 1))) throw new FailedPredicateException(this, "Precpred(Context, 1)");
						State = 268; Match(Minus);
						State = 269; multiplicativeExpression(0);
						}
						break;
					}
					} 
				}
				State = 274;
				ErrorHandler.Sync(this);
				_alt = Interpreter.AdaptivePredict(TokenStream,28,Context);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			UnrollRecursionContexts(_parentctx);
		}
		return _localctx;
	}

	public partial class RelationalExpressionContext : ParserRuleContext {
		public AdditiveExpressionContext additiveExpression() {
			return GetRuleContext<AdditiveExpressionContext>(0);
		}
		public RelationalExpressionContext relationalExpression() {
			return GetRuleContext<RelationalExpressionContext>(0);
		}
		public RelationalExpressionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_relationalExpression; } }
		public override void EnterRule(IParseTreeListener listener) {
			ILittleBigCListener typedListener = listener as ILittleBigCListener;
			if (typedListener != null) typedListener.EnterRelationalExpression(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ILittleBigCListener typedListener = listener as ILittleBigCListener;
			if (typedListener != null) typedListener.ExitRelationalExpression(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ILittleBigCVisitor<TResult> typedVisitor = visitor as ILittleBigCVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitRelationalExpression(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public RelationalExpressionContext relationalExpression() {
		return relationalExpression(0);
	}

	private RelationalExpressionContext relationalExpression(int _p) {
		ParserRuleContext _parentctx = Context;
		int _parentState = State;
		RelationalExpressionContext _localctx = new RelationalExpressionContext(Context, _parentState);
		RelationalExpressionContext _prevctx = _localctx;
		int _startState = 48;
		EnterRecursionRule(_localctx, 48, RULE_relationalExpression, _p);
		try {
			int _alt;
			EnterOuterAlt(_localctx, 1);
			{
			{
			State = 276; additiveExpression(0);
			}
			Context.Stop = TokenStream.Lt(-1);
			State = 292;
			ErrorHandler.Sync(this);
			_alt = Interpreter.AdaptivePredict(TokenStream,30,Context);
			while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.InvalidAltNumber ) {
				if ( _alt==1 ) {
					if ( ParseListeners!=null ) 
						TriggerExitRuleEvent();
					_prevctx = _localctx;
					{
					State = 290;
					switch ( Interpreter.AdaptivePredict(TokenStream,29,Context) ) {
					case 1:
						{
						_localctx = new RelationalExpressionContext(_parentctx, _parentState);
						PushNewRecursionContext(_localctx, _startState, RULE_relationalExpression);
						State = 278;
						if (!(Precpred(Context, 4))) throw new FailedPredicateException(this, "Precpred(Context, 4)");
						State = 279; Match(Less);
						State = 280; additiveExpression(0);
						}
						break;
					case 2:
						{
						_localctx = new RelationalExpressionContext(_parentctx, _parentState);
						PushNewRecursionContext(_localctx, _startState, RULE_relationalExpression);
						State = 281;
						if (!(Precpred(Context, 3))) throw new FailedPredicateException(this, "Precpred(Context, 3)");
						State = 282; Match(Greater);
						State = 283; additiveExpression(0);
						}
						break;
					case 3:
						{
						_localctx = new RelationalExpressionContext(_parentctx, _parentState);
						PushNewRecursionContext(_localctx, _startState, RULE_relationalExpression);
						State = 284;
						if (!(Precpred(Context, 2))) throw new FailedPredicateException(this, "Precpred(Context, 2)");
						State = 285; Match(LessEqual);
						State = 286; additiveExpression(0);
						}
						break;
					case 4:
						{
						_localctx = new RelationalExpressionContext(_parentctx, _parentState);
						PushNewRecursionContext(_localctx, _startState, RULE_relationalExpression);
						State = 287;
						if (!(Precpred(Context, 1))) throw new FailedPredicateException(this, "Precpred(Context, 1)");
						State = 288; Match(GreaterEqual);
						State = 289; additiveExpression(0);
						}
						break;
					}
					} 
				}
				State = 294;
				ErrorHandler.Sync(this);
				_alt = Interpreter.AdaptivePredict(TokenStream,30,Context);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			UnrollRecursionContexts(_parentctx);
		}
		return _localctx;
	}

	public partial class EqualityExpressionContext : ParserRuleContext {
		public RelationalExpressionContext relationalExpression() {
			return GetRuleContext<RelationalExpressionContext>(0);
		}
		public EqualityExpressionContext equalityExpression() {
			return GetRuleContext<EqualityExpressionContext>(0);
		}
		public EqualityExpressionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_equalityExpression; } }
		public override void EnterRule(IParseTreeListener listener) {
			ILittleBigCListener typedListener = listener as ILittleBigCListener;
			if (typedListener != null) typedListener.EnterEqualityExpression(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ILittleBigCListener typedListener = listener as ILittleBigCListener;
			if (typedListener != null) typedListener.ExitEqualityExpression(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ILittleBigCVisitor<TResult> typedVisitor = visitor as ILittleBigCVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitEqualityExpression(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public EqualityExpressionContext equalityExpression() {
		return equalityExpression(0);
	}

	private EqualityExpressionContext equalityExpression(int _p) {
		ParserRuleContext _parentctx = Context;
		int _parentState = State;
		EqualityExpressionContext _localctx = new EqualityExpressionContext(Context, _parentState);
		EqualityExpressionContext _prevctx = _localctx;
		int _startState = 50;
		EnterRecursionRule(_localctx, 50, RULE_equalityExpression, _p);
		try {
			int _alt;
			EnterOuterAlt(_localctx, 1);
			{
			{
			State = 296; relationalExpression(0);
			}
			Context.Stop = TokenStream.Lt(-1);
			State = 306;
			ErrorHandler.Sync(this);
			_alt = Interpreter.AdaptivePredict(TokenStream,32,Context);
			while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.InvalidAltNumber ) {
				if ( _alt==1 ) {
					if ( ParseListeners!=null ) 
						TriggerExitRuleEvent();
					_prevctx = _localctx;
					{
					State = 304;
					switch ( Interpreter.AdaptivePredict(TokenStream,31,Context) ) {
					case 1:
						{
						_localctx = new EqualityExpressionContext(_parentctx, _parentState);
						PushNewRecursionContext(_localctx, _startState, RULE_equalityExpression);
						State = 298;
						if (!(Precpred(Context, 2))) throw new FailedPredicateException(this, "Precpred(Context, 2)");
						State = 299; Match(Equal);
						State = 300; relationalExpression(0);
						}
						break;
					case 2:
						{
						_localctx = new EqualityExpressionContext(_parentctx, _parentState);
						PushNewRecursionContext(_localctx, _startState, RULE_equalityExpression);
						State = 301;
						if (!(Precpred(Context, 1))) throw new FailedPredicateException(this, "Precpred(Context, 1)");
						State = 302; Match(NotEqual);
						State = 303; relationalExpression(0);
						}
						break;
					}
					} 
				}
				State = 308;
				ErrorHandler.Sync(this);
				_alt = Interpreter.AdaptivePredict(TokenStream,32,Context);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			UnrollRecursionContexts(_parentctx);
		}
		return _localctx;
	}

	public partial class LogicalAndExpressionContext : ParserRuleContext {
		public EqualityExpressionContext equalityExpression() {
			return GetRuleContext<EqualityExpressionContext>(0);
		}
		public LogicalAndExpressionContext logicalAndExpression() {
			return GetRuleContext<LogicalAndExpressionContext>(0);
		}
		public LogicalAndExpressionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_logicalAndExpression; } }
		public override void EnterRule(IParseTreeListener listener) {
			ILittleBigCListener typedListener = listener as ILittleBigCListener;
			if (typedListener != null) typedListener.EnterLogicalAndExpression(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ILittleBigCListener typedListener = listener as ILittleBigCListener;
			if (typedListener != null) typedListener.ExitLogicalAndExpression(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ILittleBigCVisitor<TResult> typedVisitor = visitor as ILittleBigCVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitLogicalAndExpression(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public LogicalAndExpressionContext logicalAndExpression() {
		return logicalAndExpression(0);
	}

	private LogicalAndExpressionContext logicalAndExpression(int _p) {
		ParserRuleContext _parentctx = Context;
		int _parentState = State;
		LogicalAndExpressionContext _localctx = new LogicalAndExpressionContext(Context, _parentState);
		LogicalAndExpressionContext _prevctx = _localctx;
		int _startState = 52;
		EnterRecursionRule(_localctx, 52, RULE_logicalAndExpression, _p);
		try {
			int _alt;
			EnterOuterAlt(_localctx, 1);
			{
			{
			State = 310; equalityExpression(0);
			}
			Context.Stop = TokenStream.Lt(-1);
			State = 317;
			ErrorHandler.Sync(this);
			_alt = Interpreter.AdaptivePredict(TokenStream,33,Context);
			while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.InvalidAltNumber ) {
				if ( _alt==1 ) {
					if ( ParseListeners!=null ) 
						TriggerExitRuleEvent();
					_prevctx = _localctx;
					{
					{
					_localctx = new LogicalAndExpressionContext(_parentctx, _parentState);
					PushNewRecursionContext(_localctx, _startState, RULE_logicalAndExpression);
					State = 312;
					if (!(Precpred(Context, 1))) throw new FailedPredicateException(this, "Precpred(Context, 1)");
					State = 313; Match(AndAnd);
					State = 314; equalityExpression(0);
					}
					} 
				}
				State = 319;
				ErrorHandler.Sync(this);
				_alt = Interpreter.AdaptivePredict(TokenStream,33,Context);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			UnrollRecursionContexts(_parentctx);
		}
		return _localctx;
	}

	public partial class LogicalOrExpressionContext : ParserRuleContext {
		public LogicalAndExpressionContext logicalAndExpression() {
			return GetRuleContext<LogicalAndExpressionContext>(0);
		}
		public LogicalOrExpressionContext logicalOrExpression() {
			return GetRuleContext<LogicalOrExpressionContext>(0);
		}
		public LogicalOrExpressionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_logicalOrExpression; } }
		public override void EnterRule(IParseTreeListener listener) {
			ILittleBigCListener typedListener = listener as ILittleBigCListener;
			if (typedListener != null) typedListener.EnterLogicalOrExpression(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ILittleBigCListener typedListener = listener as ILittleBigCListener;
			if (typedListener != null) typedListener.ExitLogicalOrExpression(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ILittleBigCVisitor<TResult> typedVisitor = visitor as ILittleBigCVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitLogicalOrExpression(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public LogicalOrExpressionContext logicalOrExpression() {
		return logicalOrExpression(0);
	}

	private LogicalOrExpressionContext logicalOrExpression(int _p) {
		ParserRuleContext _parentctx = Context;
		int _parentState = State;
		LogicalOrExpressionContext _localctx = new LogicalOrExpressionContext(Context, _parentState);
		LogicalOrExpressionContext _prevctx = _localctx;
		int _startState = 54;
		EnterRecursionRule(_localctx, 54, RULE_logicalOrExpression, _p);
		try {
			int _alt;
			EnterOuterAlt(_localctx, 1);
			{
			{
			State = 321; logicalAndExpression(0);
			}
			Context.Stop = TokenStream.Lt(-1);
			State = 328;
			ErrorHandler.Sync(this);
			_alt = Interpreter.AdaptivePredict(TokenStream,34,Context);
			while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.InvalidAltNumber ) {
				if ( _alt==1 ) {
					if ( ParseListeners!=null ) 
						TriggerExitRuleEvent();
					_prevctx = _localctx;
					{
					{
					_localctx = new LogicalOrExpressionContext(_parentctx, _parentState);
					PushNewRecursionContext(_localctx, _startState, RULE_logicalOrExpression);
					State = 323;
					if (!(Precpred(Context, 1))) throw new FailedPredicateException(this, "Precpred(Context, 1)");
					State = 324; Match(OrOr);
					State = 325; logicalAndExpression(0);
					}
					} 
				}
				State = 330;
				ErrorHandler.Sync(this);
				_alt = Interpreter.AdaptivePredict(TokenStream,34,Context);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			UnrollRecursionContexts(_parentctx);
		}
		return _localctx;
	}

	public partial class AssignmentExpressionContext : ParserRuleContext {
		public LogicalOrExpressionContext logicalOrExpression() {
			return GetRuleContext<LogicalOrExpressionContext>(0);
		}
		public PostfixExpressionContext postfixExpression() {
			return GetRuleContext<PostfixExpressionContext>(0);
		}
		public AssignmentExpressionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_assignmentExpression; } }
		public override void EnterRule(IParseTreeListener listener) {
			ILittleBigCListener typedListener = listener as ILittleBigCListener;
			if (typedListener != null) typedListener.EnterAssignmentExpression(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ILittleBigCListener typedListener = listener as ILittleBigCListener;
			if (typedListener != null) typedListener.ExitAssignmentExpression(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ILittleBigCVisitor<TResult> typedVisitor = visitor as ILittleBigCVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitAssignmentExpression(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public AssignmentExpressionContext assignmentExpression() {
		AssignmentExpressionContext _localctx = new AssignmentExpressionContext(Context, State);
		EnterRule(_localctx, 56, RULE_assignmentExpression);
		try {
			State = 336;
			switch ( Interpreter.AdaptivePredict(TokenStream,35,Context) ) {
			case 1:
				EnterOuterAlt(_localctx, 1);
				{
				State = 331; logicalOrExpression(0);
				}
				break;
			case 2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 332; postfixExpression(0);
				State = 333; Match(Assign);
				State = 334; logicalOrExpression(0);
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ExpressionContext : ParserRuleContext {
		public AssignmentExpressionContext assignmentExpression() {
			return GetRuleContext<AssignmentExpressionContext>(0);
		}
		public ExpressionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_expression; } }
		public override void EnterRule(IParseTreeListener listener) {
			ILittleBigCListener typedListener = listener as ILittleBigCListener;
			if (typedListener != null) typedListener.EnterExpression(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ILittleBigCListener typedListener = listener as ILittleBigCListener;
			if (typedListener != null) typedListener.ExitExpression(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ILittleBigCVisitor<TResult> typedVisitor = visitor as ILittleBigCVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitExpression(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ExpressionContext expression() {
		ExpressionContext _localctx = new ExpressionContext(Context, State);
		EnterRule(_localctx, 58, RULE_expression);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 338; assignmentExpression();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public override bool Sempred(RuleContext _localctx, int ruleIndex, int predIndex) {
		switch (ruleIndex) {
		case 1: return translationUnit_sempred((TranslationUnitContext)_localctx, predIndex);
		case 9: return formalParameters_sempred((FormalParametersContext)_localctx, predIndex);
		case 11: return blockItemList_sempred((BlockItemListContext)_localctx, predIndex);
		case 20: return postfixExpression_sempred((PostfixExpressionContext)_localctx, predIndex);
		case 21: return argumentExpressionList_sempred((ArgumentExpressionListContext)_localctx, predIndex);
		case 22: return multiplicativeExpression_sempred((MultiplicativeExpressionContext)_localctx, predIndex);
		case 23: return additiveExpression_sempred((AdditiveExpressionContext)_localctx, predIndex);
		case 24: return relationalExpression_sempred((RelationalExpressionContext)_localctx, predIndex);
		case 25: return equalityExpression_sempred((EqualityExpressionContext)_localctx, predIndex);
		case 26: return logicalAndExpression_sempred((LogicalAndExpressionContext)_localctx, predIndex);
		case 27: return logicalOrExpression_sempred((LogicalOrExpressionContext)_localctx, predIndex);
		}
		return true;
	}
	private bool translationUnit_sempred(TranslationUnitContext _localctx, int predIndex) {
		switch (predIndex) {
		case 0: return Precpred(Context, 1);
		}
		return true;
	}
	private bool formalParameters_sempred(FormalParametersContext _localctx, int predIndex) {
		switch (predIndex) {
		case 1: return Precpred(Context, 1);
		}
		return true;
	}
	private bool blockItemList_sempred(BlockItemListContext _localctx, int predIndex) {
		switch (predIndex) {
		case 2: return Precpred(Context, 1);
		}
		return true;
	}
	private bool postfixExpression_sempred(PostfixExpressionContext _localctx, int predIndex) {
		switch (predIndex) {
		case 3: return Precpred(Context, 2);
		case 4: return Precpred(Context, 1);
		}
		return true;
	}
	private bool argumentExpressionList_sempred(ArgumentExpressionListContext _localctx, int predIndex) {
		switch (predIndex) {
		case 5: return Precpred(Context, 1);
		}
		return true;
	}
	private bool multiplicativeExpression_sempred(MultiplicativeExpressionContext _localctx, int predIndex) {
		switch (predIndex) {
		case 6: return Precpred(Context, 3);
		case 7: return Precpred(Context, 2);
		case 8: return Precpred(Context, 1);
		}
		return true;
	}
	private bool additiveExpression_sempred(AdditiveExpressionContext _localctx, int predIndex) {
		switch (predIndex) {
		case 9: return Precpred(Context, 2);
		case 10: return Precpred(Context, 1);
		}
		return true;
	}
	private bool relationalExpression_sempred(RelationalExpressionContext _localctx, int predIndex) {
		switch (predIndex) {
		case 11: return Precpred(Context, 4);
		case 12: return Precpred(Context, 3);
		case 13: return Precpred(Context, 2);
		case 14: return Precpred(Context, 1);
		}
		return true;
	}
	private bool equalityExpression_sempred(EqualityExpressionContext _localctx, int predIndex) {
		switch (predIndex) {
		case 15: return Precpred(Context, 2);
		case 16: return Precpred(Context, 1);
		}
		return true;
	}
	private bool logicalAndExpression_sempred(LogicalAndExpressionContext _localctx, int predIndex) {
		switch (predIndex) {
		case 17: return Precpred(Context, 1);
		}
		return true;
	}
	private bool logicalOrExpression_sempred(LogicalOrExpressionContext _localctx, int predIndex) {
		switch (predIndex) {
		case 18: return Precpred(Context, 1);
		}
		return true;
	}

	public static readonly string _serializedATN =
		"\x3\x430\xD6D1\x8206\xAD2D\x4417\xAEF1\x8D80\xAADD\x3\x32\x157\x4\x2\t"+
		"\x2\x4\x3\t\x3\x4\x4\t\x4\x4\x5\t\x5\x4\x6\t\x6\x4\a\t\a\x4\b\t\b\x4\t"+
		"\t\t\x4\n\t\n\x4\v\t\v\x4\f\t\f\x4\r\t\r\x4\xE\t\xE\x4\xF\t\xF\x4\x10"+
		"\t\x10\x4\x11\t\x11\x4\x12\t\x12\x4\x13\t\x13\x4\x14\t\x14\x4\x15\t\x15"+
		"\x4\x16\t\x16\x4\x17\t\x17\x4\x18\t\x18\x4\x19\t\x19\x4\x1A\t\x1A\x4\x1B"+
		"\t\x1B\x4\x1C\t\x1C\x4\x1D\t\x1D\x4\x1E\t\x1E\x4\x1F\t\x1F\x3\x2\x5\x2"+
		"@\n\x2\x3\x2\x3\x2\x3\x3\x3\x3\x3\x3\x3\x3\x3\x3\a\x3I\n\x3\f\x3\xE\x3"+
		"L\v\x3\x3\x4\x3\x4\x3\x4\x5\x4Q\n\x4\x3\x5\x3\x5\x3\x5\x3\x5\x3\x5\x5"+
		"\x5X\n\x5\x3\x6\x3\x6\x3\a\x3\a\x3\a\x3\a\x5\a`\n\a\x3\a\x3\a\x3\b\x3"+
		"\b\x3\b\x5\bg\n\b\x3\t\x3\t\x3\t\x3\t\x3\t\x3\t\x3\n\x3\n\x3\n\x3\n\x5"+
		"\ns\n\n\x3\n\x3\n\x3\n\x3\v\x3\v\x3\v\x3\v\x3\v\x3\v\a\v~\n\v\f\v\xE\v"+
		"\x81\v\v\x3\f\x3\f\x3\f\x3\r\x3\r\x3\r\x3\r\x3\r\a\r\x8B\n\r\f\r\xE\r"+
		"\x8E\v\r\x3\xE\x3\xE\x5\xE\x92\n\xE\x3\xF\x3\xF\x3\xF\x3\xF\x3\xF\x5\xF"+
		"\x99\n\xF\x3\x10\x3\x10\x5\x10\x9D\n\x10\x3\x10\x3\x10\x3\x11\x5\x11\xA2"+
		"\n\x11\x3\x11\x3\x11\x3\x12\x3\x12\x3\x12\x3\x12\x3\x12\x3\x12\x3\x12"+
		"\x5\x12\xAD\n\x12\x3\x13\x3\x13\x3\x13\x3\x13\x3\x13\x3\x13\x3\x13\x3"+
		"\x13\x3\x13\x5\x13\xB8\n\x13\x3\x13\x3\x13\x5\x13\xBC\n\x13\x3\x13\x3"+
		"\x13\x5\x13\xC0\n\x13\x3\x13\x3\x13\x5\x13\xC4\n\x13\x3\x14\x3\x14\x3"+
		"\x14\x3\x14\x3\x14\x3\x14\x5\x14\xCC\n\x14\x3\x14\x5\x14\xCF\n\x14\x3"+
		"\x15\x3\x15\x3\x15\x3\x15\x3\x15\x3\x15\x5\x15\xD7\n\x15\x3\x16\x3\x16"+
		"\x3\x16\x3\x16\x3\x16\x3\x16\x3\x16\x3\x16\x3\x16\x3\x16\x3\x16\x5\x16"+
		"\xE4\n\x16\x3\x16\a\x16\xE7\n\x16\f\x16\xE\x16\xEA\v\x16\x3\x17\x3\x17"+
		"\x3\x17\x3\x17\x3\x17\x3\x17\a\x17\xF2\n\x17\f\x17\xE\x17\xF5\v\x17\x3"+
		"\x18\x3\x18\x3\x18\x3\x18\x3\x18\x3\x18\x3\x18\x3\x18\x3\x18\x3\x18\x3"+
		"\x18\x3\x18\a\x18\x103\n\x18\f\x18\xE\x18\x106\v\x18\x3\x19\x3\x19\x3"+
		"\x19\x3\x19\x3\x19\x3\x19\x3\x19\x3\x19\x3\x19\a\x19\x111\n\x19\f\x19"+
		"\xE\x19\x114\v\x19\x3\x1A\x3\x1A\x3\x1A\x3\x1A\x3\x1A\x3\x1A\x3\x1A\x3"+
		"\x1A\x3\x1A\x3\x1A\x3\x1A\x3\x1A\x3\x1A\x3\x1A\x3\x1A\a\x1A\x125\n\x1A"+
		"\f\x1A\xE\x1A\x128\v\x1A\x3\x1B\x3\x1B\x3\x1B\x3\x1B\x3\x1B\x3\x1B\x3"+
		"\x1B\x3\x1B\x3\x1B\a\x1B\x133\n\x1B\f\x1B\xE\x1B\x136\v\x1B\x3\x1C\x3"+
		"\x1C\x3\x1C\x3\x1C\x3\x1C\x3\x1C\a\x1C\x13E\n\x1C\f\x1C\xE\x1C\x141\v"+
		"\x1C\x3\x1D\x3\x1D\x3\x1D\x3\x1D\x3\x1D\x3\x1D\a\x1D\x149\n\x1D\f\x1D"+
		"\xE\x1D\x14C\v\x1D\x3\x1E\x3\x1E\x3\x1E\x3\x1E\x3\x1E\x5\x1E\x153\n\x1E"+
		"\x3\x1F\x3\x1F\x3\x1F\x2\r\x4\x14\x18*,.\x30\x32\x34\x36\x38 \x2\x4\x6"+
		"\b\n\f\xE\x10\x12\x14\x16\x18\x1A\x1C\x1E \"$&(*,.\x30\x32\x34\x36\x38"+
		":<\x2\x3\x4\x2\b\v\xE\xE\x167\x2?\x3\x2\x2\x2\x4\x43\x3\x2\x2\x2\x6P\x3"+
		"\x2\x2\x2\bW\x3\x2\x2\x2\nY\x3\x2\x2\x2\f[\x3\x2\x2\x2\xE\x66\x3\x2\x2"+
		"\x2\x10h\x3\x2\x2\x2\x12n\x3\x2\x2\x2\x14w\x3\x2\x2\x2\x16\x82\x3\x2\x2"+
		"\x2\x18\x85\x3\x2\x2\x2\x1A\x91\x3\x2\x2\x2\x1C\x98\x3\x2\x2\x2\x1E\x9A"+
		"\x3\x2\x2\x2 \xA1\x3\x2\x2\x2\"\xA5\x3\x2\x2\x2$\xC3\x3\x2\x2\x2&\xCE"+
		"\x3\x2\x2\x2(\xD6\x3\x2\x2\x2*\xD8\x3\x2\x2\x2,\xEB\x3\x2\x2\x2.\xF6\x3"+
		"\x2\x2\x2\x30\x107\x3\x2\x2\x2\x32\x115\x3\x2\x2\x2\x34\x129\x3\x2\x2"+
		"\x2\x36\x137\x3\x2\x2\x2\x38\x142\x3\x2\x2\x2:\x152\x3\x2\x2\x2<\x154"+
		"\x3\x2\x2\x2>@\x5\x4\x3\x2?>\x3\x2\x2\x2?@\x3\x2\x2\x2@\x41\x3\x2\x2\x2"+
		"\x41\x42\a\x2\x2\x3\x42\x3\x3\x2\x2\x2\x43\x44\b\x3\x1\x2\x44\x45\x5\x6"+
		"\x4\x2\x45J\x3\x2\x2\x2\x46G\f\x3\x2\x2GI\x5\x6\x4\x2H\x46\x3\x2\x2\x2"+
		"IL\x3\x2\x2\x2JH\x3\x2\x2\x2JK\x3\x2\x2\x2K\x5\x3\x2\x2\x2LJ\x3\x2\x2"+
		"\x2MQ\x5\x12\n\x2NQ\x5\f\a\x2OQ\a%\x2\x2PM\x3\x2\x2\x2PN\x3\x2\x2\x2P"+
		"O\x3\x2\x2\x2Q\a\x3\x2\x2\x2RX\x5\n\x6\x2ST\x5\n\x6\x2TU\a\x3\x2\x2UX"+
		"\x3\x2\x2\x2VX\a\x10\x2\x2WR\x3\x2\x2\x2WS\x3\x2\x2\x2WV\x3\x2\x2\x2X"+
		"\t\x3\x2\x2\x2YZ\t\x2\x2\x2Z\v\x3\x2\x2\x2[\\\x5\b\x5\x2\\_\a+\x2\x2]"+
		"^\a\'\x2\x2^`\x5\xE\b\x2_]\x3\x2\x2\x2_`\x3\x2\x2\x2`\x61\x3\x2\x2\x2"+
		"\x61\x62\a%\x2\x2\x62\r\x3\x2\x2\x2\x63g\x5<\x1F\x2\x64g\a,\x2\x2\x65"+
		"g\x5\x10\t\x2\x66\x63\x3\x2\x2\x2\x66\x64\x3\x2\x2\x2\x66\x65\x3\x2\x2"+
		"\x2g\xF\x3\x2\x2\x2hi\a\x12\x2\x2ij\x5\n\x6\x2jk\a\x15\x2\x2kl\x5<\x1F"+
		"\x2lm\a\x16\x2\x2m\x11\x3\x2\x2\x2no\x5\b\x5\x2op\a+\x2\x2pr\a\x13\x2"+
		"\x2qs\x5\x14\v\x2rq\x3\x2\x2\x2rs\x3\x2\x2\x2st\x3\x2\x2\x2tu\a\x14\x2"+
		"\x2uv\x5\x1E\x10\x2v\x13\x3\x2\x2\x2wx\b\v\x1\x2xy\x5\x16\f\x2y\x7F\x3"+
		"\x2\x2\x2z{\f\x3\x2\x2{|\a&\x2\x2|~\x5\x16\f\x2}z\x3\x2\x2\x2~\x81\x3"+
		"\x2\x2\x2\x7F}\x3\x2\x2\x2\x7F\x80\x3\x2\x2\x2\x80\x15\x3\x2\x2\x2\x81"+
		"\x7F\x3\x2\x2\x2\x82\x83\x5\b\x5\x2\x83\x84\a+\x2\x2\x84\x17\x3\x2\x2"+
		"\x2\x85\x86\b\r\x1\x2\x86\x87\x5\x1A\xE\x2\x87\x8C\x3\x2\x2\x2\x88\x89"+
		"\f\x3\x2\x2\x89\x8B\x5\x1A\xE\x2\x8A\x88\x3\x2\x2\x2\x8B\x8E\x3\x2\x2"+
		"\x2\x8C\x8A\x3\x2\x2\x2\x8C\x8D\x3\x2\x2\x2\x8D\x19\x3\x2\x2\x2\x8E\x8C"+
		"\x3\x2\x2\x2\x8F\x92\x5\f\a\x2\x90\x92\x5\x1C\xF\x2\x91\x8F\x3\x2\x2\x2"+
		"\x91\x90\x3\x2\x2\x2\x92\x1B\x3\x2\x2\x2\x93\x99\x5\x1E\x10\x2\x94\x99"+
		"\x5 \x11\x2\x95\x99\x5\"\x12\x2\x96\x99\x5$\x13\x2\x97\x99\x5&\x14\x2"+
		"\x98\x93\x3\x2\x2\x2\x98\x94\x3\x2\x2\x2\x98\x95\x3\x2\x2\x2\x98\x96\x3"+
		"\x2\x2\x2\x98\x97\x3\x2\x2\x2\x99\x1D\x3\x2\x2\x2\x9A\x9C\a\x17\x2\x2"+
		"\x9B\x9D\x5\x18\r\x2\x9C\x9B\x3\x2\x2\x2\x9C\x9D\x3\x2\x2\x2\x9D\x9E\x3"+
		"\x2\x2\x2\x9E\x9F\a\x18\x2\x2\x9F\x1F\x3\x2\x2\x2\xA0\xA2\x5<\x1F\x2\xA1"+
		"\xA0\x3\x2\x2\x2\xA1\xA2\x3\x2\x2\x2\xA2\xA3\x3\x2\x2\x2\xA3\xA4\a%\x2"+
		"\x2\xA4!\x3\x2\x2\x2\xA5\xA6\a\r\x2\x2\xA6\xA7\a\x13\x2\x2\xA7\xA8\x5"+
		"<\x1F\x2\xA8\xA9\a\x14\x2\x2\xA9\xAC\x5\x1C\xF\x2\xAA\xAB\a\a\x2\x2\xAB"+
		"\xAD\x5\x1C\xF\x2\xAC\xAA\x3\x2\x2\x2\xAC\xAD\x3\x2\x2\x2\xAD#\x3\x2\x2"+
		"\x2\xAE\xAF\a\x11\x2\x2\xAF\xB0\a\x13\x2\x2\xB0\xB1\x5<\x1F\x2\xB1\xB2"+
		"\a\x14\x2\x2\xB2\xB3\x5\x1C\xF\x2\xB3\xC4\x3\x2\x2\x2\xB4\xB5\a\f\x2\x2"+
		"\xB5\xB7\a\x13\x2\x2\xB6\xB8\x5<\x1F\x2\xB7\xB6\x3\x2\x2\x2\xB7\xB8\x3"+
		"\x2\x2\x2\xB8\xB9\x3\x2\x2\x2\xB9\xBB\a%\x2\x2\xBA\xBC\x5<\x1F\x2\xBB"+
		"\xBA\x3\x2\x2\x2\xBB\xBC\x3\x2\x2\x2\xBC\xBD\x3\x2\x2\x2\xBD\xBF\a%\x2"+
		"\x2\xBE\xC0\x5<\x1F\x2\xBF\xBE\x3\x2\x2\x2\xBF\xC0\x3\x2\x2\x2\xC0\xC1"+
		"\x3\x2\x2\x2\xC1\xC2\a\x14\x2\x2\xC2\xC4\x5\x1C\xF\x2\xC3\xAE\x3\x2\x2"+
		"\x2\xC3\xB4\x3\x2\x2\x2\xC4%\x3\x2\x2\x2\xC5\xC6\a\x6\x2\x2\xC6\xCF\a"+
		"%\x2\x2\xC7\xC8\a\x4\x2\x2\xC8\xCF\a%\x2\x2\xC9\xCB\a\xF\x2\x2\xCA\xCC"+
		"\x5<\x1F\x2\xCB\xCA\x3\x2\x2\x2\xCB\xCC\x3\x2\x2\x2\xCC\xCD\x3\x2\x2\x2"+
		"\xCD\xCF\a%\x2\x2\xCE\xC5\x3\x2\x2\x2\xCE\xC7\x3\x2\x2\x2\xCE\xC9\x3\x2"+
		"\x2\x2\xCF\'\x3\x2\x2\x2\xD0\xD7\a+\x2\x2\xD1\xD7\a,\x2\x2\xD2\xD3\a\x13"+
		"\x2\x2\xD3\xD4\x5<\x1F\x2\xD4\xD5\a\x14\x2\x2\xD5\xD7\x3\x2\x2\x2\xD6"+
		"\xD0\x3\x2\x2\x2\xD6\xD1\x3\x2\x2\x2\xD6\xD2\x3\x2\x2\x2\xD7)\x3\x2\x2"+
		"\x2\xD8\xD9\b\x16\x1\x2\xD9\xDA\x5(\x15\x2\xDA\xE8\x3\x2\x2\x2\xDB\xDC"+
		"\f\x4\x2\x2\xDC\xDD\a\x15\x2\x2\xDD\xDE\x5<\x1F\x2\xDE\xDF\a\x16\x2\x2"+
		"\xDF\xE7\x3\x2\x2\x2\xE0\xE1\f\x3\x2\x2\xE1\xE3\a\x13\x2\x2\xE2\xE4\x5"+
		",\x17\x2\xE3\xE2\x3\x2\x2\x2\xE3\xE4\x3\x2\x2\x2\xE4\xE5\x3\x2\x2\x2\xE5"+
		"\xE7\a\x14\x2\x2\xE6\xDB\x3\x2\x2\x2\xE6\xE0\x3\x2\x2\x2\xE7\xEA\x3\x2"+
		"\x2\x2\xE8\xE6\x3\x2\x2\x2\xE8\xE9\x3\x2\x2\x2\xE9+\x3\x2\x2\x2\xEA\xE8"+
		"\x3\x2\x2\x2\xEB\xEC\b\x17\x1\x2\xEC\xED\x5:\x1E\x2\xED\xF3\x3\x2\x2\x2"+
		"\xEE\xEF\f\x3\x2\x2\xEF\xF0\a&\x2\x2\xF0\xF2\x5:\x1E\x2\xF1\xEE\x3\x2"+
		"\x2\x2\xF2\xF5\x3\x2\x2\x2\xF3\xF1\x3\x2\x2\x2\xF3\xF4\x3\x2\x2\x2\xF4"+
		"-\x3\x2\x2\x2\xF5\xF3\x3\x2\x2\x2\xF6\xF7\b\x18\x1\x2\xF7\xF8\x5*\x16"+
		"\x2\xF8\x104\x3\x2\x2\x2\xF9\xFA\f\x5\x2\x2\xFA\xFB\a\x1F\x2\x2\xFB\x103"+
		"\x5*\x16\x2\xFC\xFD\f\x4\x2\x2\xFD\xFE\a \x2\x2\xFE\x103\x5*\x16\x2\xFF"+
		"\x100\f\x3\x2\x2\x100\x101\a!\x2\x2\x101\x103\x5*\x16\x2\x102\xF9\x3\x2"+
		"\x2\x2\x102\xFC\x3\x2\x2\x2\x102\xFF\x3\x2\x2\x2\x103\x106\x3\x2\x2\x2"+
		"\x104\x102\x3\x2\x2\x2\x104\x105\x3\x2\x2\x2\x105/\x3\x2\x2\x2\x106\x104"+
		"\x3\x2\x2\x2\x107\x108\b\x19\x1\x2\x108\x109\x5.\x18\x2\x109\x112\x3\x2"+
		"\x2\x2\x10A\x10B\f\x4\x2\x2\x10B\x10C\a\x1D\x2\x2\x10C\x111\x5.\x18\x2"+
		"\x10D\x10E\f\x3\x2\x2\x10E\x10F\a\x1E\x2\x2\x10F\x111\x5.\x18\x2\x110"+
		"\x10A\x3\x2\x2\x2\x110\x10D\x3\x2\x2\x2\x111\x114\x3\x2\x2\x2\x112\x110"+
		"\x3\x2\x2\x2\x112\x113\x3\x2\x2\x2\x113\x31\x3\x2\x2\x2\x114\x112\x3\x2"+
		"\x2\x2\x115\x116\b\x1A\x1\x2\x116\x117\x5\x30\x19\x2\x117\x126\x3\x2\x2"+
		"\x2\x118\x119\f\x6\x2\x2\x119\x11A\a\x19\x2\x2\x11A\x125\x5\x30\x19\x2"+
		"\x11B\x11C\f\x5\x2\x2\x11C\x11D\a\x1B\x2\x2\x11D\x125\x5\x30\x19\x2\x11E"+
		"\x11F\f\x4\x2\x2\x11F\x120\a\x1A\x2\x2\x120\x125\x5\x30\x19\x2\x121\x122"+
		"\f\x3\x2\x2\x122\x123\a\x1C\x2\x2\x123\x125\x5\x30\x19\x2\x124\x118\x3"+
		"\x2\x2\x2\x124\x11B\x3\x2\x2\x2\x124\x11E\x3\x2\x2\x2\x124\x121\x3\x2"+
		"\x2\x2\x125\x128\x3\x2\x2\x2\x126\x124\x3\x2\x2\x2\x126\x127\x3\x2\x2"+
		"\x2\x127\x33\x3\x2\x2\x2\x128\x126\x3\x2\x2\x2\x129\x12A\b\x1B\x1\x2\x12A"+
		"\x12B\x5\x32\x1A\x2\x12B\x134\x3\x2\x2\x2\x12C\x12D\f\x4\x2\x2\x12D\x12E"+
		"\a(\x2\x2\x12E\x133\x5\x32\x1A\x2\x12F\x130\f\x3\x2\x2\x130\x131\a)\x2"+
		"\x2\x131\x133\x5\x32\x1A\x2\x132\x12C\x3\x2\x2\x2\x132\x12F\x3\x2\x2\x2"+
		"\x133\x136\x3\x2\x2\x2\x134\x132\x3\x2\x2\x2\x134\x135\x3\x2\x2\x2\x135"+
		"\x35\x3\x2\x2\x2\x136\x134\x3\x2\x2\x2\x137\x138\b\x1C\x1\x2\x138\x139"+
		"\x5\x34\x1B\x2\x139\x13F\x3\x2\x2\x2\x13A\x13B\f\x3\x2\x2\x13B\x13C\a"+
		"\"\x2\x2\x13C\x13E\x5\x34\x1B\x2\x13D\x13A\x3\x2\x2\x2\x13E\x141\x3\x2"+
		"\x2\x2\x13F\x13D\x3\x2\x2\x2\x13F\x140\x3\x2\x2\x2\x140\x37\x3\x2\x2\x2"+
		"\x141\x13F\x3\x2\x2\x2\x142\x143\b\x1D\x1\x2\x143\x144\x5\x36\x1C\x2\x144"+
		"\x14A\x3\x2\x2\x2\x145\x146\f\x3\x2\x2\x146\x147\a#\x2\x2\x147\x149\x5"+
		"\x36\x1C\x2\x148\x145\x3\x2\x2\x2\x149\x14C\x3\x2\x2\x2\x14A\x148\x3\x2"+
		"\x2\x2\x14A\x14B\x3\x2\x2\x2\x14B\x39\x3\x2\x2\x2\x14C\x14A\x3\x2\x2\x2"+
		"\x14D\x153\x5\x38\x1D\x2\x14E\x14F\x5*\x16\x2\x14F\x150\a\'\x2\x2\x150"+
		"\x151\x5\x38\x1D\x2\x151\x153\x3\x2\x2\x2\x152\x14D\x3\x2\x2\x2\x152\x14E"+
		"\x3\x2\x2\x2\x153;\x3\x2\x2\x2\x154\x155\x5:\x1E\x2\x155=\x3\x2\x2\x2"+
		"&?JPW_\x66r\x7F\x8C\x91\x98\x9C\xA1\xAC\xB7\xBB\xBF\xC3\xCB\xCE\xD6\xE3"+
		"\xE6\xE8\xF3\x102\x104\x110\x112\x124\x126\x132\x134\x13F\x14A\x152";
	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN.ToCharArray());
}
